name: Hub command
description: Run a command (deploy, plan, etc.) for a particular hub

inputs:
  aws-access-key-id:
    required: true
  aws-secret-access-key:
    required: true
  ssh-private-key:
    required: true
  dockerhub-username:
    required: true
  dockerhub-password:
    required: true
  command:
    required: true
  healthcheck:
    required: false

runs:
  using: composite

  steps:
    # Allow pushing images to ECR
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        mask-aws-account-id: no
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: 'us-east-1'
    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # For pulling images from Docker Hub without hitting rate limits
    - run: docker login --username ${{ inputs.dockerhub-username }} --password ${{ inputs.dockerhub-password }}
      shell: bash

    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}

    - run: ${{ inputs.command }}
      shell: bash
      env:
        EARTHLY_SECRETS: "AWS_ACCESS_KEY_ID=${{ inputs.aws-access-key-id }},AWS_SECRET_ACCESS_KEY=${{ inputs.aws-secret-access-key }}"
        EARTHLY_VERBOSE: true

    - if: ${{ inputs.healthcheck }}
      name: Check health
      uses: nick-fields/retry@v3
      with:
        max_attempts: 30
        timeout_minutes: 2
        shell: bash
        command: ${{ inputs.healthcheck }}
        warning_on_retry: false
