/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IdRegistry } from './IdRegistry.js';
export * as factories from './factories/index.js';
export { IdRegistry__factory } from './factories/IdRegistry__factory.js';
