/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IdRegistry } from "./IdRegistry";
export * as factories from "./factories";
export { IdRegistry__factory } from "./factories/IdRegistry__factory";
