name: Perform Action
run-name: ${{ inputs.action }} by @${{ github.actor }}

on:
  workflow_call:
    secrets:
      TERRAFORM_AWS_ACCESS_KEY_ID:
        required: false # Not needed for image builds
      TERRAFORM_AWS_SECRET_ACCESS_KEY:
        required: false # Not needed for image builds
      STACK_DEPLOY_SSH_PRIVATE_KEY:
        required: true
      FARCASTERXYZ_DOCKER_HUB_USER:
        required: true
      FARCASTERXYZ_DOCKER_HUB_TOKEN:
        required: true
    inputs:
      action:
        description: Action to perform
        required: true
        type: string

  workflow_dispatch:
    inputs:
      action:
        description: Action to perform
        required: true
        type: choice
        options:
          - build
          - plan
          - deploy

jobs:
  action:
    runs-on: [earthly-satellite#runner1]
    name: ${{ inputs.action }}
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Set release ID
        id: set-release
        run: |
          release=$(date -u +"%Y-%m-%dT%H-%M-%S-%3NZ")
          echo "release = $release"
          echo "release=$release" >> "$GITHUB_OUTPUT"

      - name: Set commit hash
        id: set-commit-hash
        run: |
          commit_hash=$(git rev-parse HEAD)
          echo "commit_hash = $commit_hash"
          echo "commit_hash=$commit_hash" >> "$GITHUB_OUTPUT"

      - name: Execute ${{ inputs.action }}
        uses: ./.github/actions/command
        with:
          aws-access-key-id: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
          ssh-private-key: ${{ secrets.STACK_DEPLOY_SSH_PRIVATE_KEY }}
          dockerhub-username: ${{ secrets.FARCASTERXYZ_DOCKER_HUB_USER }}
          dockerhub-password: ${{ secrets.FARCASTERXYZ_DOCKER_HUB_TOKEN }}
          command: make ${{ inputs.action }} ref=${{ steps.set-commit-hash.outputs.commit_hash }} release=${{ steps.set-release.outputs.release }}
          healthcheck: curl --fail https://fnames.farcaster.xyz/_health
